on:
  pull_request:
    types: [closed]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: idk
    steps:
      - name: Hello world action step
        id: hello
        uses: danielmklein/instrument-ci@main
        env:
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
          NEW_RELIC_APP_NAME: "GitHub Actions Test"
